#!/bin/bash
# noted-managed Rscript launcher for R {version}
# ---------------------------------------------------------------
# Generated by noted into <env_path>/bin/Rscript at env creation
# time. Mirrors the env vars that the kernel (ark or IRkernel)
# receives via runtime.json kernel_env, so running an .R script
# from the file editor sees the same R version, renv library, and
# system packages as the notebook cells do.
#
# Do not edit by hand - this file is overwritten on env creation.

export R_HOME="/opt/R/{version}/lib/R"
export LD_LIBRARY_PATH="/opt/R/{version}/lib/R/lib"
export R_PROFILE_USER="{env_path}/.Rprofile"
export RENV_PATHS_LIBRARY="{env_path}/renv/library"
export RENV_PATHS_LOCKFILE="{env_path}/renv.lock"
export RENV_CONFIG_EXTERNAL_LIBRARIES="/opt/R/{version}/lib/R/library"
export RENV_CONFIG_SYNCHRONIZED_CHECK="FALSE"
export RENV_PATHS_CACHE="/app/data/.renv-cache"
export NOTED_PROJECT_ROOT="${PWD}"

exec /opt/R/{version}/bin/Rscript "$@"
